steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - express_server
  - --source=api/cloud_functions/
  - --runtime=nodejs18
  - --region=asia-northeast1
  - --entry-point=expressServer
  - --trigger-http
  - --allow-unauthenticated