steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - express_server
  - --runtime=nodejs18
  - --region=asia-northeast1
  - --entry-point=expressServer
  - --trigger-http