steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - express_server
  - --runtime
  - nodejs20
  - --region
  - asia-northeast1
  - --entry-point
  - express_server
  - --source
  - api/cloud_functions