steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['run','init:functions']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - express_server
  - --runtime=nodejs20
  - --region=asia-northeast1
  - --entry-point=handler
  - --trigger-http
  - --allow-unauthenticated