steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['COPY', './env/.env.cloudfunctions','./.env']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - express_server
  - --runtime=nodejs20
  - --region=asia-northeast1
  - --entry-point=expressServer
  - --trigger-http
  - --allow-unauthenticated
  env:
  - 'DEPLOY_SERVER=cloudfunctions'