const MOVED_PERMANENTLY = 301;
const OK = 200;
const INTERNAL_SERVER_ERROR = 500;
const BAD_REQUEST = 400;
const TEMPORARY_REDIRECT = 307;
const GONE = 410;

module.exports = {
  MOVED_PERMANENTLY,
  OK,
  INTERNAL_SERVER_ERROR,
  BAD_REQUEST,
  TEMPORARY_REDIRECT,
  GONE,
};
